Algoritmo "crescente"

VAR

   x, y : inteiro


Inicio

   escreval("Digite dois números: ")
   leia(x)
   leia(y)
   
   enquanto x > y faca
      escreval("DECRESCENTE!")
      escreval("Digite outros dois números:")
      leia(x)
      leia(y)
   fimenquanto
   
      enquanto x < y faca
         escreval("CRESCENTE")
         escreval("Digite outros dois numeros:")
         leia(x)
         leia(y)
      fimenquanto


   se x = y entao
   fimse


         


Fimalgoritmo